package JoinTree;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufStats.proto

public final class ProtobufStats {
  private ProtobufStats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TableOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 size = 2;
    /**
     * <code>optional int32 size = 2;</code>
     *
     * <pre>
     * number of elements
     * </pre>
     */
    boolean hasSize();
    /**
     * <code>optional int32 size = 2;</code>
     *
     * <pre>
     * number of elements
     * </pre>
     */
    int getSize();

    // optional bool isComplex = 3;
    /**
     * <code>optional bool isComplex = 3;</code>
     *
     * <pre>
     * if for the same subject exist more values
     * </pre>
     */
    boolean hasIsComplex();
    /**
     * <code>optional bool isComplex = 3;</code>
     *
     * <pre>
     * if for the same subject exist more values
     * </pre>
     */
    boolean getIsComplex();

    // optional int32 distinctSubjects = 4;
    /**
     * <code>optional int32 distinctSubjects = 4;</code>
     *
     * <pre>
     * distinct subjects in that table
     * </pre>
     */
    boolean hasDistinctSubjects();
    /**
     * <code>optional int32 distinctSubjects = 4;</code>
     *
     * <pre>
     * distinct subjects in that table
     * </pre>
     */
    int getDistinctSubjects();
  }
  /**
   * Protobuf type {@code Table}
   *
   * <pre>
   * describe a single table (belonging to particular property)
   * </pre>
   */
  public static final class Table extends
      com.google.protobuf.GeneratedMessage
      implements TableOrBuilder {
    // Use Table.newBuilder() to construct.
    private Table(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Table(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Table defaultInstance;
    public static Table getDefaultInstance() {
      return defaultInstance;
    }

    public Table getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Table(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              size_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isComplex_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              distinctSubjects_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufStats.internal_static_Table_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufStats.internal_static_Table_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtobufStats.Table.class, ProtobufStats.Table.Builder.class);
    }

    public static com.google.protobuf.Parser<Table> PARSER =
        new com.google.protobuf.AbstractParser<Table>() {
      public Table parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Table(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Table> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 size = 2;
    public static final int SIZE_FIELD_NUMBER = 2;
    private int size_;
    /**
     * <code>optional int32 size = 2;</code>
     *
     * <pre>
     * number of elements
     * </pre>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 size = 2;</code>
     *
     * <pre>
     * number of elements
     * </pre>
     */
    public int getSize() {
      return size_;
    }

    // optional bool isComplex = 3;
    public static final int ISCOMPLEX_FIELD_NUMBER = 3;
    private boolean isComplex_;
    /**
     * <code>optional bool isComplex = 3;</code>
     *
     * <pre>
     * if for the same subject exist more values
     * </pre>
     */
    public boolean hasIsComplex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool isComplex = 3;</code>
     *
     * <pre>
     * if for the same subject exist more values
     * </pre>
     */
    public boolean getIsComplex() {
      return isComplex_;
    }

    // optional int32 distinctSubjects = 4;
    public static final int DISTINCTSUBJECTS_FIELD_NUMBER = 4;
    private int distinctSubjects_;
    /**
     * <code>optional int32 distinctSubjects = 4;</code>
     *
     * <pre>
     * distinct subjects in that table
     * </pre>
     */
    public boolean hasDistinctSubjects() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 distinctSubjects = 4;</code>
     *
     * <pre>
     * distinct subjects in that table
     * </pre>
     */
    public int getDistinctSubjects() {
      return distinctSubjects_;
    }

    private void initFields() {
      name_ = "";
      size_ = 0;
      isComplex_ = false;
      distinctSubjects_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, size_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isComplex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, distinctSubjects_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, size_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isComplex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, distinctSubjects_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtobufStats.Table parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufStats.Table parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufStats.Table parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufStats.Table parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufStats.Table parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtobufStats.Table parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtobufStats.Table parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtobufStats.Table parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtobufStats.Table parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtobufStats.Table parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtobufStats.Table prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Table}
     *
     * <pre>
     * describe a single table (belonging to particular property)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtobufStats.TableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufStats.internal_static_Table_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufStats.internal_static_Table_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtobufStats.Table.class, ProtobufStats.Table.Builder.class);
      }

      // Construct using ProtobufStats.Table.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isComplex_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        distinctSubjects_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufStats.internal_static_Table_descriptor;
      }

      public ProtobufStats.Table getDefaultInstanceForType() {
        return ProtobufStats.Table.getDefaultInstance();
      }

      public ProtobufStats.Table build() {
        ProtobufStats.Table result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtobufStats.Table buildPartial() {
        ProtobufStats.Table result = new ProtobufStats.Table(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isComplex_ = isComplex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.distinctSubjects_ = distinctSubjects_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtobufStats.Table) {
          return mergeFrom((ProtobufStats.Table)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtobufStats.Table other) {
        if (other == ProtobufStats.Table.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasIsComplex()) {
          setIsComplex(other.getIsComplex());
        }
        if (other.hasDistinctSubjects()) {
          setDistinctSubjects(other.getDistinctSubjects());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtobufStats.Table parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtobufStats.Table) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 size = 2;
      private int size_ ;
      /**
       * <code>optional int32 size = 2;</code>
       *
       * <pre>
       * number of elements
       * </pre>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 size = 2;</code>
       *
       * <pre>
       * number of elements
       * </pre>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>optional int32 size = 2;</code>
       *
       * <pre>
       * number of elements
       * </pre>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000002;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 size = 2;</code>
       *
       * <pre>
       * number of elements
       * </pre>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        onChanged();
        return this;
      }

      // optional bool isComplex = 3;
      private boolean isComplex_ ;
      /**
       * <code>optional bool isComplex = 3;</code>
       *
       * <pre>
       * if for the same subject exist more values
       * </pre>
       */
      public boolean hasIsComplex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool isComplex = 3;</code>
       *
       * <pre>
       * if for the same subject exist more values
       * </pre>
       */
      public boolean getIsComplex() {
        return isComplex_;
      }
      /**
       * <code>optional bool isComplex = 3;</code>
       *
       * <pre>
       * if for the same subject exist more values
       * </pre>
       */
      public Builder setIsComplex(boolean value) {
        bitField0_ |= 0x00000004;
        isComplex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isComplex = 3;</code>
       *
       * <pre>
       * if for the same subject exist more values
       * </pre>
       */
      public Builder clearIsComplex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isComplex_ = false;
        onChanged();
        return this;
      }

      // optional int32 distinctSubjects = 4;
      private int distinctSubjects_ ;
      /**
       * <code>optional int32 distinctSubjects = 4;</code>
       *
       * <pre>
       * distinct subjects in that table
       * </pre>
       */
      public boolean hasDistinctSubjects() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 distinctSubjects = 4;</code>
       *
       * <pre>
       * distinct subjects in that table
       * </pre>
       */
      public int getDistinctSubjects() {
        return distinctSubjects_;
      }
      /**
       * <code>optional int32 distinctSubjects = 4;</code>
       *
       * <pre>
       * distinct subjects in that table
       * </pre>
       */
      public Builder setDistinctSubjects(int value) {
        bitField0_ |= 0x00000008;
        distinctSubjects_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 distinctSubjects = 4;</code>
       *
       * <pre>
       * distinct subjects in that table
       * </pre>
       */
      public Builder clearDistinctSubjects() {
        bitField0_ = (bitField0_ & ~0x00000008);
        distinctSubjects_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Table)
    }

    static {
      defaultInstance = new Table(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Table)
  }

  public interface GraphOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 size = 2;
    /**
     * <code>optional int32 size = 2;</code>
     *
     * <pre>
     * number of triples
     * </pre>
     */
    boolean hasSize();
    /**
     * <code>optional int32 size = 2;</code>
     *
     * <pre>
     * number of triples
     * </pre>
     */
    int getSize();

    // optional int32 distinctSubjects = 3;
    /**
     * <code>optional int32 distinctSubjects = 3;</code>
     *
     * <pre>
     * distinct subjects in the whole graph
     * </pre>
     */
    boolean hasDistinctSubjects();
    /**
     * <code>optional int32 distinctSubjects = 3;</code>
     *
     * <pre>
     * distinct subjects in the whole graph
     * </pre>
     */
    int getDistinctSubjects();

    // repeated .Table tables = 4;
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    java.util.List<ProtobufStats.Table> 
        getTablesList();
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    ProtobufStats.Table getTables(int index);
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    int getTablesCount();
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    java.util.List<? extends ProtobufStats.TableOrBuilder> 
        getTablesOrBuilderList();
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    ProtobufStats.TableOrBuilder getTablesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Graph}
   *
   * <pre>
   * definition for the whole Graph
   * </pre>
   */
  public static final class Graph extends
      com.google.protobuf.GeneratedMessage
      implements GraphOrBuilder {
    // Use Graph.newBuilder() to construct.
    private Graph(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Graph(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Graph defaultInstance;
    public static Graph getDefaultInstance() {
      return defaultInstance;
    }

    public Graph getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Graph(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              size_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              distinctSubjects_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                tables_ = new java.util.ArrayList<ProtobufStats.Table>();
                mutable_bitField0_ |= 0x00000008;
              }
              tables_.add(input.readMessage(ProtobufStats.Table.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          tables_ = java.util.Collections.unmodifiableList(tables_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufStats.internal_static_Graph_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufStats.internal_static_Graph_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtobufStats.Graph.class, ProtobufStats.Graph.Builder.class);
    }

    public static com.google.protobuf.Parser<Graph> PARSER =
        new com.google.protobuf.AbstractParser<Graph>() {
      public Graph parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Graph(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Graph> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 size = 2;
    public static final int SIZE_FIELD_NUMBER = 2;
    private int size_;
    /**
     * <code>optional int32 size = 2;</code>
     *
     * <pre>
     * number of triples
     * </pre>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 size = 2;</code>
     *
     * <pre>
     * number of triples
     * </pre>
     */
    public int getSize() {
      return size_;
    }

    // optional int32 distinctSubjects = 3;
    public static final int DISTINCTSUBJECTS_FIELD_NUMBER = 3;
    private int distinctSubjects_;
    /**
     * <code>optional int32 distinctSubjects = 3;</code>
     *
     * <pre>
     * distinct subjects in the whole graph
     * </pre>
     */
    public boolean hasDistinctSubjects() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 distinctSubjects = 3;</code>
     *
     * <pre>
     * distinct subjects in the whole graph
     * </pre>
     */
    public int getDistinctSubjects() {
      return distinctSubjects_;
    }

    // repeated .Table tables = 4;
    public static final int TABLES_FIELD_NUMBER = 4;
    private java.util.List<ProtobufStats.Table> tables_;
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    public java.util.List<ProtobufStats.Table> getTablesList() {
      return tables_;
    }
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    public java.util.List<? extends ProtobufStats.TableOrBuilder> 
        getTablesOrBuilderList() {
      return tables_;
    }
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    public int getTablesCount() {
      return tables_.size();
    }
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    public ProtobufStats.Table getTables(int index) {
      return tables_.get(index);
    }
    /**
     * <code>repeated .Table tables = 4;</code>
     */
    public ProtobufStats.TableOrBuilder getTablesOrBuilder(
        int index) {
      return tables_.get(index);
    }

    private void initFields() {
      name_ = "";
      size_ = 0;
      distinctSubjects_ = 0;
      tables_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getTablesCount(); i++) {
        if (!getTables(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, size_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, distinctSubjects_);
      }
      for (int i = 0; i < tables_.size(); i++) {
        output.writeMessage(4, tables_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, size_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, distinctSubjects_);
      }
      for (int i = 0; i < tables_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, tables_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtobufStats.Graph parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufStats.Graph parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufStats.Graph parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufStats.Graph parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufStats.Graph parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtobufStats.Graph parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtobufStats.Graph parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtobufStats.Graph parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtobufStats.Graph parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtobufStats.Graph parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtobufStats.Graph prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Graph}
     *
     * <pre>
     * definition for the whole Graph
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtobufStats.GraphOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufStats.internal_static_Graph_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufStats.internal_static_Graph_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtobufStats.Graph.class, ProtobufStats.Graph.Builder.class);
      }

      // Construct using ProtobufStats.Graph.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTablesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        distinctSubjects_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (tablesBuilder_ == null) {
          tables_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          tablesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufStats.internal_static_Graph_descriptor;
      }

      public ProtobufStats.Graph getDefaultInstanceForType() {
        return ProtobufStats.Graph.getDefaultInstance();
      }

      public ProtobufStats.Graph build() {
        ProtobufStats.Graph result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtobufStats.Graph buildPartial() {
        ProtobufStats.Graph result = new ProtobufStats.Graph(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.distinctSubjects_ = distinctSubjects_;
        if (tablesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            tables_ = java.util.Collections.unmodifiableList(tables_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.tables_ = tables_;
        } else {
          result.tables_ = tablesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtobufStats.Graph) {
          return mergeFrom((ProtobufStats.Graph)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtobufStats.Graph other) {
        if (other == ProtobufStats.Graph.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasDistinctSubjects()) {
          setDistinctSubjects(other.getDistinctSubjects());
        }
        if (tablesBuilder_ == null) {
          if (!other.tables_.isEmpty()) {
            if (tables_.isEmpty()) {
              tables_ = other.tables_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTablesIsMutable();
              tables_.addAll(other.tables_);
            }
            onChanged();
          }
        } else {
          if (!other.tables_.isEmpty()) {
            if (tablesBuilder_.isEmpty()) {
              tablesBuilder_.dispose();
              tablesBuilder_ = null;
              tables_ = other.tables_;
              bitField0_ = (bitField0_ & ~0x00000008);
              tablesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTablesFieldBuilder() : null;
            } else {
              tablesBuilder_.addAllMessages(other.tables_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getTablesCount(); i++) {
          if (!getTables(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtobufStats.Graph parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtobufStats.Graph) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 size = 2;
      private int size_ ;
      /**
       * <code>optional int32 size = 2;</code>
       *
       * <pre>
       * number of triples
       * </pre>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 size = 2;</code>
       *
       * <pre>
       * number of triples
       * </pre>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>optional int32 size = 2;</code>
       *
       * <pre>
       * number of triples
       * </pre>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000002;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 size = 2;</code>
       *
       * <pre>
       * number of triples
       * </pre>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        onChanged();
        return this;
      }

      // optional int32 distinctSubjects = 3;
      private int distinctSubjects_ ;
      /**
       * <code>optional int32 distinctSubjects = 3;</code>
       *
       * <pre>
       * distinct subjects in the whole graph
       * </pre>
       */
      public boolean hasDistinctSubjects() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 distinctSubjects = 3;</code>
       *
       * <pre>
       * distinct subjects in the whole graph
       * </pre>
       */
      public int getDistinctSubjects() {
        return distinctSubjects_;
      }
      /**
       * <code>optional int32 distinctSubjects = 3;</code>
       *
       * <pre>
       * distinct subjects in the whole graph
       * </pre>
       */
      public Builder setDistinctSubjects(int value) {
        bitField0_ |= 0x00000004;
        distinctSubjects_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 distinctSubjects = 3;</code>
       *
       * <pre>
       * distinct subjects in the whole graph
       * </pre>
       */
      public Builder clearDistinctSubjects() {
        bitField0_ = (bitField0_ & ~0x00000004);
        distinctSubjects_ = 0;
        onChanged();
        return this;
      }

      // repeated .Table tables = 4;
      private java.util.List<ProtobufStats.Table> tables_ =
        java.util.Collections.emptyList();
      private void ensureTablesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          tables_ = new java.util.ArrayList<ProtobufStats.Table>(tables_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ProtobufStats.Table, ProtobufStats.Table.Builder, ProtobufStats.TableOrBuilder> tablesBuilder_;

      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public java.util.List<ProtobufStats.Table> getTablesList() {
        if (tablesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tables_);
        } else {
          return tablesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public int getTablesCount() {
        if (tablesBuilder_ == null) {
          return tables_.size();
        } else {
          return tablesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public ProtobufStats.Table getTables(int index) {
        if (tablesBuilder_ == null) {
          return tables_.get(index);
        } else {
          return tablesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder setTables(
          int index, ProtobufStats.Table value) {
        if (tablesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTablesIsMutable();
          tables_.set(index, value);
          onChanged();
        } else {
          tablesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder setTables(
          int index, ProtobufStats.Table.Builder builderForValue) {
        if (tablesBuilder_ == null) {
          ensureTablesIsMutable();
          tables_.set(index, builderForValue.build());
          onChanged();
        } else {
          tablesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder addTables(ProtobufStats.Table value) {
        if (tablesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTablesIsMutable();
          tables_.add(value);
          onChanged();
        } else {
          tablesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder addTables(
          int index, ProtobufStats.Table value) {
        if (tablesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTablesIsMutable();
          tables_.add(index, value);
          onChanged();
        } else {
          tablesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder addTables(
          ProtobufStats.Table.Builder builderForValue) {
        if (tablesBuilder_ == null) {
          ensureTablesIsMutable();
          tables_.add(builderForValue.build());
          onChanged();
        } else {
          tablesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder addTables(
          int index, ProtobufStats.Table.Builder builderForValue) {
        if (tablesBuilder_ == null) {
          ensureTablesIsMutable();
          tables_.add(index, builderForValue.build());
          onChanged();
        } else {
          tablesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder addAllTables(
          java.lang.Iterable<? extends ProtobufStats.Table> values) {
        if (tablesBuilder_ == null) {
          ensureTablesIsMutable();
          super.addAll(values, tables_);
          onChanged();
        } else {
          tablesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder clearTables() {
        if (tablesBuilder_ == null) {
          tables_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          tablesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public Builder removeTables(int index) {
        if (tablesBuilder_ == null) {
          ensureTablesIsMutable();
          tables_.remove(index);
          onChanged();
        } else {
          tablesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public ProtobufStats.Table.Builder getTablesBuilder(
          int index) {
        return getTablesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public ProtobufStats.TableOrBuilder getTablesOrBuilder(
          int index) {
        if (tablesBuilder_ == null) {
          return tables_.get(index);  } else {
          return tablesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public java.util.List<? extends ProtobufStats.TableOrBuilder> 
           getTablesOrBuilderList() {
        if (tablesBuilder_ != null) {
          return tablesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tables_);
        }
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public ProtobufStats.Table.Builder addTablesBuilder() {
        return getTablesFieldBuilder().addBuilder(
            ProtobufStats.Table.getDefaultInstance());
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public ProtobufStats.Table.Builder addTablesBuilder(
          int index) {
        return getTablesFieldBuilder().addBuilder(
            index, ProtobufStats.Table.getDefaultInstance());
      }
      /**
       * <code>repeated .Table tables = 4;</code>
       */
      public java.util.List<ProtobufStats.Table.Builder> 
           getTablesBuilderList() {
        return getTablesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtobufStats.Table, ProtobufStats.Table.Builder, ProtobufStats.TableOrBuilder> 
          getTablesFieldBuilder() {
        if (tablesBuilder_ == null) {
          tablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtobufStats.Table, ProtobufStats.Table.Builder, ProtobufStats.TableOrBuilder>(
                  tables_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          tables_ = null;
        }
        return tablesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Graph)
    }

    static {
      defaultInstance = new Graph(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Graph)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Table_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Table_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Graph_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Graph_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ProtobufStats.proto\"P\n\005Table\022\014\n\004name\030\001" +
      " \002(\t\022\014\n\004size\030\002 \001(\005\022\021\n\tisComplex\030\003 \001(\010\022\030\n" +
      "\020distinctSubjects\030\004 \001(\005\"U\n\005Graph\022\014\n\004name" +
      "\030\001 \001(\t\022\014\n\004size\030\002 \001(\005\022\030\n\020distinctSubjects" +
      "\030\003 \001(\005\022\026\n\006tables\030\004 \003(\0132\006.Table"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Table_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Table_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Table_descriptor,
              new java.lang.String[] { "Name", "Size", "IsComplex", "DistinctSubjects", });
          internal_static_Graph_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Graph_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Graph_descriptor,
              new java.lang.String[] { "Name", "Size", "DistinctSubjects", "Tables", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
