// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufStats.proto
package joinTree;

public final class ProtobufStats {
	private ProtobufStats() {
	}

	public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface TableStatsOrBuilder extends
			// @@protoc_insertion_point(interface_extends:TableStats)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>optional string name = 1;</code>
		 */
		java.lang.String getName();

		/**
		 * <code>optional string name = 1;</code>
		 */
		com.google.protobuf.ByteString getNameBytes();

		/**
		 * <pre>
		 * number of elements
		 * </pre>
		 *
		 * <code>optional int32 size = 2;</code>
		 */
		int getSize();

		/**
		 * <pre>
		 * if for the same subject exist more values
		 * </pre>
		 *
		 * <code>optional bool isComplex = 3;</code>
		 */
		boolean getIsComplex();

		/**
		 * <pre>
		 * distinct subjects in that table
		 * </pre>
		 *
		 * <code>optional int32 distinctSubjects = 4;</code>
		 */
		int getDistinctSubjects();
	}

	/**
	 * Protobuf type {@code TableStats}
	 */
	public static final class TableStats extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:TableStats)
			TableStatsOrBuilder {
		// Use TableStats.newBuilder() to construct.
		private TableStats(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private TableStats() {
			name_ = "";
			size_ = 0;
			isComplex_ = false;
			distinctSubjects_ = 0;
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private TableStats(final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			@SuppressWarnings("unused")
			final int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						final java.lang.String s = input.readStringRequireUtf8();

						name_ = s;
						break;
					}
					case 16: {

						size_ = input.readInt32();
						break;
					}
					case 24: {

						isComplex_ = input.readBool();
						break;
					}
					case 32: {

						distinctSubjects_ = input.readInt32();
						break;
					}
					}
				}
			} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (final java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return ProtobufStats.internal_static_TableStats_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return ProtobufStats.internal_static_TableStats_fieldAccessorTable.ensureFieldAccessorsInitialized(
					ProtobufStats.TableStats.class, ProtobufStats.TableStats.Builder.class);
		}

		public static final int NAME_FIELD_NUMBER = 1;
		private volatile java.lang.Object name_;

		/**
		 * <code>optional string name = 1;</code>
		 */
		@Override
		public java.lang.String getName() {
			final java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final java.lang.String s = bs.toStringUtf8();
				name_ = s;
				return s;
			}
		}

		/**
		 * <code>optional string name = 1;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getNameBytes() {
			final java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				final com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int SIZE_FIELD_NUMBER = 2;
		private int size_;

		/**
		 * <pre>
		 * number of elements
		 * </pre>
		 *
		 * <code>optional int32 size = 2;</code>
		 */
		@Override
		public int getSize() {
			return size_;
		}

		public static final int ISCOMPLEX_FIELD_NUMBER = 3;
		private boolean isComplex_;

		/**
		 * <pre>
		 * if for the same subject exist more values
		 * </pre>
		 *
		 * <code>optional bool isComplex = 3;</code>
		 */
		@Override
		public boolean getIsComplex() {
			return isComplex_;
		}

		public static final int DISTINCTSUBJECTS_FIELD_NUMBER = 4;
		private int distinctSubjects_;

		/**
		 * <pre>
		 * distinct subjects in that table
		 * </pre>
		 *
		 * <code>optional int32 distinctSubjects = 4;</code>
		 */
		@Override
		public int getDistinctSubjects() {
			return distinctSubjects_;
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(final com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (!getNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
			}
			if (size_ != 0) {
				output.writeInt32(2, size_);
			}
			if (isComplex_ != false) {
				output.writeBool(3, isComplex_);
			}
			if (distinctSubjects_ != 0) {
				output.writeInt32(4, distinctSubjects_);
			}
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (!getNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
			}
			if (size_ != 0) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, size_);
			}
			if (isComplex_ != false) {
				size += com.google.protobuf.CodedOutputStream.computeBoolSize(3, isComplex_);
			}
			if (distinctSubjects_ != 0) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(4, distinctSubjects_);
			}
			memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof ProtobufStats.TableStats)) {
				return super.equals(obj);
			}
			final ProtobufStats.TableStats other = (ProtobufStats.TableStats) obj;

			boolean result = true;
			result = result && getName().equals(other.getName());
			result = result && (getSize() == other.getSize());
			result = result && (getIsComplex() == other.getIsComplex());
			result = result && (getDistinctSubjects() == other.getDistinctSubjects());
			return result;
		}

		@SuppressWarnings("unchecked")
		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptorForType().hashCode();
			hash = (37 * hash) + NAME_FIELD_NUMBER;
			hash = (53 * hash) + getName().hashCode();
			hash = (37 * hash) + SIZE_FIELD_NUMBER;
			hash = (53 * hash) + getSize();
			hash = (37 * hash) + ISCOMPLEX_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getIsComplex());
			hash = (37 * hash) + DISTINCTSUBJECTS_FIELD_NUMBER;
			hash = (53 * hash) + getDistinctSubjects();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static ProtobufStats.TableStats parseFrom(final com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static ProtobufStats.TableStats parseFrom(final com.google.protobuf.ByteString data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static ProtobufStats.TableStats parseFrom(final byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static ProtobufStats.TableStats parseFrom(final byte[] data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static ProtobufStats.TableStats parseFrom(final java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static ProtobufStats.TableStats parseFrom(final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static ProtobufStats.TableStats parseDelimitedFrom(final java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static ProtobufStats.TableStats parseDelimitedFrom(final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static ProtobufStats.TableStats parseFrom(final com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static ProtobufStats.TableStats parseFrom(final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(final ProtobufStats.TableStats prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code TableStats}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:TableStats)
				ProtobufStats.TableStatsOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return ProtobufStats.internal_static_TableStats_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return ProtobufStats.internal_static_TableStats_fieldAccessorTable.ensureFieldAccessorsInitialized(
						ProtobufStats.TableStats.class, ProtobufStats.TableStats.Builder.class);
			}

			// Construct using ProtobufStats.TableStats.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				name_ = "";

				size_ = 0;

				isComplex_ = false;

				distinctSubjects_ = 0;

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return ProtobufStats.internal_static_TableStats_descriptor;
			}

			@Override
			public ProtobufStats.TableStats getDefaultInstanceForType() {
				return ProtobufStats.TableStats.getDefaultInstance();
			}

			@Override
			public ProtobufStats.TableStats build() {
				final ProtobufStats.TableStats result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public ProtobufStats.TableStats buildPartial() {
				final ProtobufStats.TableStats result = new ProtobufStats.TableStats(this);
				result.name_ = name_;
				result.size_ = size_;
				result.isComplex_ = isComplex_;
				result.distinctSubjects_ = distinctSubjects_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return super.clone();
			}

			@Override
			public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field, final Object value) {
				return super.setField(field, value);
			}

			@Override
			public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@Override
			public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
					final int index, final Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
					final Object value) {
				return super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.Message other) {
				if (other instanceof ProtobufStats.TableStats) {
					return mergeFrom((ProtobufStats.TableStats) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(final ProtobufStats.TableStats other) {
				if (other == ProtobufStats.TableStats.getDefaultInstance()) {
					return this;
				}
				if (!other.getName().isEmpty()) {
					name_ = other.name_;
					onChanged();
				}
				if (other.getSize() != 0) {
					setSize(other.getSize());
				}
				if (other.getIsComplex() != false) {
					setIsComplex(other.getIsComplex());
				}
				if (other.getDistinctSubjects() != 0) {
					setDistinctSubjects(other.getDistinctSubjects());
				}
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				ProtobufStats.TableStats parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (ProtobufStats.TableStats) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private java.lang.Object name_ = "";

			/**
			 * <code>optional string name = 1;</code>
			 */
			@Override
			public java.lang.String getName() {
				final java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					final java.lang.String s = bs.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getNameBytes() {
				final java.lang.Object ref = name_;
				if (ref instanceof String) {
					final com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder setName(final java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder clearName() {

				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder setNameBytes(final com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				name_ = value;
				onChanged();
				return this;
			}

			private int size_;

			/**
			 * <pre>
			 * number of elements
			 * </pre>
			 *
			 * <code>optional int32 size = 2;</code>
			 */
			@Override
			public int getSize() {
				return size_;
			}

			/**
			 * <pre>
			 * number of elements
			 * </pre>
			 *
			 * <code>optional int32 size = 2;</code>
			 */
			public Builder setSize(final int value) {

				size_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * number of elements
			 * </pre>
			 *
			 * <code>optional int32 size = 2;</code>
			 */
			public Builder clearSize() {

				size_ = 0;
				onChanged();
				return this;
			}

			private boolean isComplex_;

			/**
			 * <pre>
			 * if for the same subject exist more values
			 * </pre>
			 *
			 * <code>optional bool isComplex = 3;</code>
			 */
			@Override
			public boolean getIsComplex() {
				return isComplex_;
			}

			/**
			 * <pre>
			 * if for the same subject exist more values
			 * </pre>
			 *
			 * <code>optional bool isComplex = 3;</code>
			 */
			public Builder setIsComplex(final boolean value) {

				isComplex_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * if for the same subject exist more values
			 * </pre>
			 *
			 * <code>optional bool isComplex = 3;</code>
			 */
			public Builder clearIsComplex() {

				isComplex_ = false;
				onChanged();
				return this;
			}

			private int distinctSubjects_;

			/**
			 * <pre>
			 * distinct subjects in that table
			 * </pre>
			 *
			 * <code>optional int32 distinctSubjects = 4;</code>
			 */
			@Override
			public int getDistinctSubjects() {
				return distinctSubjects_;
			}

			/**
			 * <pre>
			 * distinct subjects in that table
			 * </pre>
			 *
			 * <code>optional int32 distinctSubjects = 4;</code>
			 */
			public Builder setDistinctSubjects(final int value) {

				distinctSubjects_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * distinct subjects in that table
			 * </pre>
			 *
			 * <code>optional int32 distinctSubjects = 4;</code>
			 */
			public Builder clearDistinctSubjects() {

				distinctSubjects_ = 0;
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			@Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:TableStats)
		}

		// @@protoc_insertion_point(class_scope:TableStats)
		private static final ProtobufStats.TableStats DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new ProtobufStats.TableStats();
		}

		public static ProtobufStats.TableStats getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<TableStats> PARSER =
				new com.google.protobuf.AbstractParser<TableStats>() {
					@Override
					public TableStats parsePartialFrom(final com.google.protobuf.CodedInputStream input,
							final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
						return new TableStats(input, extensionRegistry);
					}
				};

		public static com.google.protobuf.Parser<TableStats> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<TableStats> getParserForType() {
			return PARSER;
		}

		@Override
		public ProtobufStats.TableStats getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

		public Boolean isInverseComplex() {
			// TODO Auto-generated method stub
			return null;
		}

	}

	public interface GraphOrBuilder extends
			// @@protoc_insertion_point(interface_extends:Graph)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>optional string name = 1;</code>
		 */
		java.lang.String getName();

		/**
		 * <code>optional string name = 1;</code>
		 */
		com.google.protobuf.ByteString getNameBytes();

		/**
		 * <code>optional bool arePrefixesActive = 2;</code>
		 */
		boolean getArePrefixesActive();

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		java.util.List<ProtobufStats.TableStats> getTablesList();

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		ProtobufStats.TableStats getTables(int index);

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		int getTablesCount();

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		java.util.List<? extends ProtobufStats.TableStatsOrBuilder> getTablesOrBuilderList();

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		ProtobufStats.TableStatsOrBuilder getTablesOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code Graph}
	 */
	public static final class Graph extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:Graph)
			GraphOrBuilder {
		// Use Graph.newBuilder() to construct.
		private Graph(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Graph() {
			name_ = "";
			arePrefixesActive_ = false;
			tables_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private Graph(final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						final java.lang.String s = input.readStringRequireUtf8();

						name_ = s;
						break;
					}
					case 16: {

						arePrefixesActive_ = input.readBool();
						break;
					}
					case 26: {
						if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
							tables_ = new java.util.ArrayList<>();
							mutable_bitField0_ |= 0x00000004;
						}
						tables_.add(input.readMessage(ProtobufStats.TableStats.parser(), extensionRegistry));
						break;
					}
					}
				}
			} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (final java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
					tables_ = java.util.Collections.unmodifiableList(tables_);
				}
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return ProtobufStats.internal_static_Graph_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return ProtobufStats.internal_static_Graph_fieldAccessorTable
					.ensureFieldAccessorsInitialized(ProtobufStats.Graph.class, ProtobufStats.Graph.Builder.class);
		}

		@SuppressWarnings("unused")
		private int bitField0_;
		public static final int NAME_FIELD_NUMBER = 1;
		private volatile java.lang.Object name_;

		/**
		 * <code>optional string name = 1;</code>
		 */
		@Override
		public java.lang.String getName() {
			final java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final java.lang.String s = bs.toStringUtf8();
				name_ = s;
				return s;
			}
		}

		/**
		 * <code>optional string name = 1;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getNameBytes() {
			final java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				final com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int AREPREFIXESACTIVE_FIELD_NUMBER = 2;
		private boolean arePrefixesActive_;

		/**
		 * <code>optional bool arePrefixesActive = 2;</code>
		 */
		@Override
		public boolean getArePrefixesActive() {
			return arePrefixesActive_;
		}

		public static final int TABLES_FIELD_NUMBER = 3;
		private java.util.List<ProtobufStats.TableStats> tables_;

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		@Override
		public java.util.List<ProtobufStats.TableStats> getTablesList() {
			return tables_;
		}

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		@Override
		public java.util.List<? extends ProtobufStats.TableStatsOrBuilder> getTablesOrBuilderList() {
			return tables_;
		}

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		@Override
		public int getTablesCount() {
			return tables_.size();
		}

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		@Override
		public ProtobufStats.TableStats getTables(final int index) {
			return tables_.get(index);
		}

		/**
		 * <code>repeated .TableStats tables = 3;</code>
		 */
		@Override
		public ProtobufStats.TableStatsOrBuilder getTablesOrBuilder(final int index) {
			return tables_.get(index);
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(final com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (!getNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
			}
			if (arePrefixesActive_ != false) {
				output.writeBool(2, arePrefixesActive_);
			}
			for (int i = 0; i < tables_.size(); i++) {
				output.writeMessage(3, tables_.get(i));
			}
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (!getNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
			}
			if (arePrefixesActive_ != false) {
				size += com.google.protobuf.CodedOutputStream.computeBoolSize(2, arePrefixesActive_);
			}
			for (int i = 0; i < tables_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, tables_.get(i));
			}
			memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof ProtobufStats.Graph)) {
				return super.equals(obj);
			}
			final ProtobufStats.Graph other = (ProtobufStats.Graph) obj;

			boolean result = true;
			result = result && getName().equals(other.getName());
			result = result && (getArePrefixesActive() == other.getArePrefixesActive());
			result = result && getTablesList().equals(other.getTablesList());
			return result;
		}

		@SuppressWarnings("unchecked")
		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptorForType().hashCode();
			hash = (37 * hash) + NAME_FIELD_NUMBER;
			hash = (53 * hash) + getName().hashCode();
			hash = (37 * hash) + AREPREFIXESACTIVE_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getArePrefixesActive());
			if (getTablesCount() > 0) {
				hash = (37 * hash) + TABLES_FIELD_NUMBER;
				hash = (53 * hash) + getTablesList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static ProtobufStats.Graph parseFrom(final com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static ProtobufStats.Graph parseFrom(final com.google.protobuf.ByteString data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static ProtobufStats.Graph parseFrom(final byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static ProtobufStats.Graph parseFrom(final byte[] data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static ProtobufStats.Graph parseFrom(final java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static ProtobufStats.Graph parseFrom(final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static ProtobufStats.Graph parseDelimitedFrom(final java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static ProtobufStats.Graph parseDelimitedFrom(final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static ProtobufStats.Graph parseFrom(final com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static ProtobufStats.Graph parseFrom(final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(final ProtobufStats.Graph prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code Graph}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:Graph)
				ProtobufStats.GraphOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return ProtobufStats.internal_static_Graph_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return ProtobufStats.internal_static_Graph_fieldAccessorTable
						.ensureFieldAccessorsInitialized(ProtobufStats.Graph.class, ProtobufStats.Graph.Builder.class);
			}

			// Construct using ProtobufStats.Graph.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					getTablesFieldBuilder();
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				name_ = "";

				arePrefixesActive_ = false;

				if (tablesBuilder_ == null) {
					tables_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
				} else {
					tablesBuilder_.clear();
				}
				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return ProtobufStats.internal_static_Graph_descriptor;
			}

			@Override
			public ProtobufStats.Graph getDefaultInstanceForType() {
				return ProtobufStats.Graph.getDefaultInstance();
			}

			@Override
			public ProtobufStats.Graph build() {
				final ProtobufStats.Graph result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public ProtobufStats.Graph buildPartial() {
				final ProtobufStats.Graph result = new ProtobufStats.Graph(this);
				@SuppressWarnings("unused")
				final int from_bitField0_ = bitField0_;
				final int to_bitField0_ = 0;
				result.name_ = name_;
				result.arePrefixesActive_ = arePrefixesActive_;
				if (tablesBuilder_ == null) {
					if (((bitField0_ & 0x00000004) == 0x00000004)) {
						tables_ = java.util.Collections.unmodifiableList(tables_);
						bitField0_ = (bitField0_ & ~0x00000004);
					}
					result.tables_ = tables_;
				} else {
					result.tables_ = tablesBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return super.clone();
			}

			@Override
			public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field, final Object value) {
				return super.setField(field, value);
			}

			@Override
			public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@Override
			public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
					final int index, final Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
					final Object value) {
				return super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.Message other) {
				if (other instanceof ProtobufStats.Graph) {
					return mergeFrom((ProtobufStats.Graph) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(final ProtobufStats.Graph other) {
				if (other == ProtobufStats.Graph.getDefaultInstance()) {
					return this;
				}
				if (!other.getName().isEmpty()) {
					name_ = other.name_;
					onChanged();
				}
				if (other.getArePrefixesActive() != false) {
					setArePrefixesActive(other.getArePrefixesActive());
				}
				if (tablesBuilder_ == null) {
					if (!other.tables_.isEmpty()) {
						if (tables_.isEmpty()) {
							tables_ = other.tables_;
							bitField0_ = (bitField0_ & ~0x00000004);
						} else {
							ensureTablesIsMutable();
							tables_.addAll(other.tables_);
						}
						onChanged();
					}
				} else {
					if (!other.tables_.isEmpty()) {
						if (tablesBuilder_.isEmpty()) {
							tablesBuilder_.dispose();
							tablesBuilder_ = null;
							tables_ = other.tables_;
							bitField0_ = (bitField0_ & ~0x00000004);
							tablesBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? getTablesFieldBuilder()
									: null;
						} else {
							tablesBuilder_.addAllMessages(other.tables_);
						}
					}
				}
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				ProtobufStats.Graph parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (ProtobufStats.Graph) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object name_ = "";

			/**
			 * <code>optional string name = 1;</code>
			 */
			@Override
			public java.lang.String getName() {
				final java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					final java.lang.String s = bs.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getNameBytes() {
				final java.lang.Object ref = name_;
				if (ref instanceof String) {
					final com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder setName(final java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder clearName() {

				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string name = 1;</code>
			 */
			public Builder setNameBytes(final com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				name_ = value;
				onChanged();
				return this;
			}

			private boolean arePrefixesActive_;

			/**
			 * <code>optional bool arePrefixesActive = 2;</code>
			 */
			@Override
			public boolean getArePrefixesActive() {
				return arePrefixesActive_;
			}

			/**
			 * <code>optional bool arePrefixesActive = 2;</code>
			 */
			public Builder setArePrefixesActive(final boolean value) {

				arePrefixesActive_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional bool arePrefixesActive = 2;</code>
			 */
			public Builder clearArePrefixesActive() {

				arePrefixesActive_ = false;
				onChanged();
				return this;
			}

			private java.util.List<ProtobufStats.TableStats> tables_ = java.util.Collections.emptyList();

			private void ensureTablesIsMutable() {
				if (!((bitField0_ & 0x00000004) == 0x00000004)) {
					tables_ = new java.util.ArrayList<>(tables_);
					bitField0_ |= 0x00000004;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<ProtobufStats.TableStats, ProtobufStats.TableStats.Builder, ProtobufStats.TableStatsOrBuilder> tablesBuilder_;

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			@Override
			public java.util.List<ProtobufStats.TableStats> getTablesList() {
				if (tablesBuilder_ == null) {
					return java.util.Collections.unmodifiableList(tables_);
				} else {
					return tablesBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			@Override
			public int getTablesCount() {
				if (tablesBuilder_ == null) {
					return tables_.size();
				} else {
					return tablesBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			@Override
			public ProtobufStats.TableStats getTables(final int index) {
				if (tablesBuilder_ == null) {
					return tables_.get(index);
				} else {
					return tablesBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder setTables(final int index, final ProtobufStats.TableStats value) {
				if (tablesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureTablesIsMutable();
					tables_.set(index, value);
					onChanged();
				} else {
					tablesBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder setTables(final int index, final ProtobufStats.TableStats.Builder builderForValue) {
				if (tablesBuilder_ == null) {
					ensureTablesIsMutable();
					tables_.set(index, builderForValue.build());
					onChanged();
				} else {
					tablesBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder addTables(final ProtobufStats.TableStats value) {
				if (tablesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureTablesIsMutable();
					tables_.add(value);
					onChanged();
				} else {
					tablesBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder addTables(final int index, final ProtobufStats.TableStats value) {
				if (tablesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureTablesIsMutable();
					tables_.add(index, value);
					onChanged();
				} else {
					tablesBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder addTables(final ProtobufStats.TableStats.Builder builderForValue) {
				if (tablesBuilder_ == null) {
					ensureTablesIsMutable();
					tables_.add(builderForValue.build());
					onChanged();
				} else {
					tablesBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder addTables(final int index, final ProtobufStats.TableStats.Builder builderForValue) {
				if (tablesBuilder_ == null) {
					ensureTablesIsMutable();
					tables_.add(index, builderForValue.build());
					onChanged();
				} else {
					tablesBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder addAllTables(final java.lang.Iterable<? extends ProtobufStats.TableStats> values) {
				if (tablesBuilder_ == null) {
					ensureTablesIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, tables_);
					onChanged();
				} else {
					tablesBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder clearTables() {
				if (tablesBuilder_ == null) {
					tables_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
					onChanged();
				} else {
					tablesBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public Builder removeTables(final int index) {
				if (tablesBuilder_ == null) {
					ensureTablesIsMutable();
					tables_.remove(index);
					onChanged();
				} else {
					tablesBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public ProtobufStats.TableStats.Builder getTablesBuilder(final int index) {
				return getTablesFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			@Override
			public ProtobufStats.TableStatsOrBuilder getTablesOrBuilder(final int index) {
				if (tablesBuilder_ == null) {
					return tables_.get(index);
				} else {
					return tablesBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			@Override
			public java.util.List<? extends ProtobufStats.TableStatsOrBuilder> getTablesOrBuilderList() {
				if (tablesBuilder_ != null) {
					return tablesBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(tables_);
				}
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public ProtobufStats.TableStats.Builder addTablesBuilder() {
				return getTablesFieldBuilder().addBuilder(ProtobufStats.TableStats.getDefaultInstance());
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public ProtobufStats.TableStats.Builder addTablesBuilder(final int index) {
				return getTablesFieldBuilder().addBuilder(index, ProtobufStats.TableStats.getDefaultInstance());
			}

			/**
			 * <code>repeated .TableStats tables = 3;</code>
			 */
			public java.util.List<ProtobufStats.TableStats.Builder> getTablesBuilderList() {
				return getTablesFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<ProtobufStats.TableStats, ProtobufStats.TableStats.Builder, ProtobufStats.TableStatsOrBuilder>
					getTablesFieldBuilder() {
				if (tablesBuilder_ == null) {
					tablesBuilder_ =
							new com.google.protobuf.RepeatedFieldBuilderV3<>(
									tables_, ((bitField0_ & 0x00000004) == 0x00000004), getParentForChildren(),
									isClean());
					tables_ = null;
				}
				return tablesBuilder_;
			}

			@Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			@Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:Graph)
		}

		// @@protoc_insertion_point(class_scope:Graph)
		private static final ProtobufStats.Graph DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new ProtobufStats.Graph();
		}

		public static ProtobufStats.Graph getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Graph> PARSER =
				new com.google.protobuf.AbstractParser<Graph>() {
					@Override
					public Graph parsePartialFrom(final com.google.protobuf.CodedInputStream input,
							final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
						return new Graph(input, extensionRegistry);
					}
				};

		public static com.google.protobuf.Parser<Graph> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Graph> getParserForType() {
			return PARSER;
		}

		@Override
		public ProtobufStats.Graph getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_TableStats_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_TableStats_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_Graph_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Graph_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		final java.lang.String[] descriptorData = { "\n\023ProtobufStats.proto\"U\n\nTableStats\022\014\n\004n"
				+ "ame\030\001 \001(\t\022\014\n\004size\030\002 \001(\005\022\021\n\tisComplex\030\003 \001"
				+ "(\010\022\030\n\020distinctSubjects\030\004 \001(\005\"M\n\005Graph\022\014\n"
				+ "\004name\030\001 \001(\t\022\031\n\021arePrefixesActive\030\002 \001(\010\022\033"
				+ "\n\006tables\030\003 \003(\0132\013.TableStatsb\006proto3" };
		final com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					@Override
					public com.google.protobuf.ExtensionRegistry
							assignDescriptors(final com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_TableStats_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_TableStats_fieldAccessorTable =
				new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_TableStats_descriptor,
						new java.lang.String[] { "Name", "Size", "IsComplex", "DistinctSubjects", });
		internal_static_Graph_descriptor = getDescriptor().getMessageTypes().get(1);
		internal_static_Graph_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_Graph_descriptor, new java.lang.String[] { "Name", "ArePrefixesActive", "Tables", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
